plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://reasoning-machine.github.io
baseurl: /geminit

title: Reasoning Machine
description: This is a machine that reasons.

machine:
  name: Reasoning-Machine
  verb: Reasoning
  instructions_file: reasoning_geminit.md
  token: gemini_paid
  server: https://localhost:443
  apiUrl: https://generativelanguage.googleapis.com/v1beta/models/
  fallback_llm: gemini-3-flash-preview

app:
  worker_name: gemapi.js

lm:
  model: gemini-3-pro-preview
  maxOutputTokens: 65536
  temperature: 1.0
  topP: 0.9
  topK: 50
  thinkingLevel: high
  includeThoughts: true


github_settings:
  owner: reasoning-machine
  repo: reasoning_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
